///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String flagsUsa = 'assets/flags/usa.png';
  static const String iconsApple = 'assets/icons/apple.png';
  static const String iconsBack = 'assets/icons/back.png';
  static const String iconsBottomHomeDark = 'assets/icons/bottom_home_dark.png';
  static const String iconsBottomHomeLight = 'assets/icons/bottom_home_light.png';
  static const String iconsBottomPersonDark = 'assets/icons/bottom_person_dark.png';
  static const String iconsBottomPersonLight = 'assets/icons/bottom_person_light.png';
  static const String iconsBottomRidesDark = 'assets/icons/bottom_rides_dark.png';
  static const String iconsBottomRidesLight = 'assets/icons/bottom_rides_light.png';
  static const String iconsBottomSearchDark = 'assets/icons/bottom_search_dark.png';
  static const String iconsBottomSearchLight = 'assets/icons/bottom_search_light.png';
  static const String iconsCalendar = 'assets/icons/calendar.png';
  static const String iconsFacebook = 'assets/icons/facebook.png';
  static const String iconsGoogle = 'assets/icons/google.png';
  static const String iconsGreyLine = 'assets/icons/grey_line.png';
  static const String iconsHistoryAddress = 'assets/icons/history_address.png';
  static const String iconsHomeAddress = 'assets/icons/home_address.png';
  static const String iconsHomeExploreCar = 'assets/icons/home_explore_car.png';
  static const String iconsLocation = 'assets/icons/location.png';
  static const String iconsMore = 'assets/icons/more.png';
  static const String iconsNavigationIcon = 'assets/icons/navigation_icon.png';
  static const String iconsProfilePicturePlaceholder = 'assets/icons/profile_picture_placeholder.png';
  static const String iconsSavedAddress = 'assets/icons/saved_address.png';
  static const String iconsSearch = 'assets/icons/search.png';
  static const String iconsWorkAddress = 'assets/icons/work_address.png';
  static const String imagesBackground = 'assets/images/background.png';
  static const String imagesClock = 'assets/images/clock.png';
  static const String imagesLight1 = 'assets/images/light-1.png';
  static const String imagesLight2 = 'assets/images/light-2.png';
  static const String languagesEn = 'assets/languages/en.json';
  static const String logosLogo = 'assets/logos/logo.png';

}
